kind: Deployment
apiVersion: apps/v1
metadata:
  name: petclinicclus
  labels:
    app: petclinicclus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinicclus
  template:
    metadata:
      labels:
        app:  petclinicclus
    spec:
      containers:
        - name: petclinicclus
          image: skumarjira/petimage
          ports:
            - containerPort: 8080