kind: Deployment
apiVersion: apps/v1
metadata:
  name: petshopp
  labels:
    app: petshoppp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petshoppp
  template:
    metadata:
      labels:
        app:  petshoppp
    spec:
      containers:
        - name: petcontainer
          image: himanshu0/petclinic
          ports:
            - containerPort: 8080
